package ServerClient;

public class Server {
	
	/*IMPORTANT FUNCTIONS*/
	public boolean CHALLENGE(int rand) {
		// TODO: Sent by server to challenge client to authenticate self. New rand generated every challenge.
		return true; // FIXME: Need to return proper value, or return earlier.
	}
	
	public void AUTH_SUCCESS(int rand_cookie, int port_number) {
		// TODO: Sent by server to notify the client authentication was successful. rand_cookie is rand generated by server, por_number is TCP port assigned by server for subsequent connection by client.
	}
	
	public void AUTH_FAIL() {
		// TODO: Sent by server to notify the client authentication has failed.
	}
	
	public void CONNECTED() {
		// TODO: Sent by the server to notify the client it has been connected.
	}
	
	/*Everything Else*/
	
}
